######################################################
#
# XPS Tcl API script generated by PlanAhead
#
######################################################

cd "H:/github/zedboard_project/xilinx_lab/lab6/lab6.srcs/sources_1/edk/sytem"
if { [xload new sytem.xmp] != 0 } {
  exit -1
}
xset arch zynq
xset dev xc7z020
xset package clg484
xset speedgrade -1

xset binfo ZEDBOARD

if { [xset hier sub] != 0 } {
  exit -1
}
xset hdl vhdl
save proj
exit
