
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 14.4 EDK_P.49d
* DO NOT EDIT.
*
* Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

* 
* Description: Profiling Configuration parameters. These parameters
* can be overwritten thru run configuration in SDK
*
*******************************************************************/

#ifndef _PROFILE_CONFIG_H
#define _PROFILE_CONFIG_H

#define BINSIZE 4
#define CPU_FREQ_HZ 666666688
#define SAMPLE_FREQ_HZ 100000
#define TIMER_CLK_TICKS 6666
#define PROC_CORTEXA9 1
#define ENABLE_SCU_TIMER 1
#define ENABLE_SYS_INTR 1
#define PROFILE_TIMER_BASEADDR 0xF8F00600
#define PROFILE_TIMER_INTR_ID 29
#define SCUGIC_CPU_BASEADDR 0xF8F00100
#define SCUGIC_DIST_BASEADDR 0xF8F01000

#endif

/******************************************************************/

