
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 14.4 EDK_P.49d
* DO NOT EDIT.
*
* Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xbram.h"

/*
* The configuration table for devices
*/

XBram_Config XBram_ConfigTable[] =
{
	{
		XPAR_AXI_BRAM_CTRL_0_DEVICE_ID,
		XPAR_AXI_BRAM_CTRL_0_DATA_WIDTH,
		XPAR_AXI_BRAM_CTRL_0_ECC,
		XPAR_AXI_BRAM_CTRL_0_FAULT_INJECT,
		XPAR_AXI_BRAM_CTRL_0_CE_FAILING_REGISTERS,
		0,
		XPAR_AXI_BRAM_CTRL_0_UE_FAILING_REGISTERS,
		0,
		XPAR_AXI_BRAM_CTRL_0_ECC_STATUS_REGISTERS,
		XPAR_AXI_BRAM_CTRL_0_CE_COUNTER_WIDTH,
		XPAR_AXI_BRAM_CTRL_0_ECC_ONOFF_REGISTER,
		XPAR_AXI_BRAM_CTRL_0_ECC_ONOFF_RESET_VALUE,
		XPAR_AXI_BRAM_CTRL_0_WRITE_ACCESS,
		XPAR_AXI_BRAM_CTRL_0_S_AXI_BASEADDR,
		XPAR_AXI_BRAM_CTRL_0_S_AXI_HIGHADDR
	}
};


