# Tcl script generated by PlanAhead

set reloadAllCoreGenRepositories true

set tclUtilsPath "c:/Xilinx/14.4/ISE_DS/PlanAhead/scripts/pa_cg_utils.tcl"

set repoPaths ""

set cgIndexMapPath "C:/xup/adv_embedded/labs/lab2/lab1.srcs/sources_1/ip/cg_nt_index_map.xml"

set cgProjectPath "c:/xup/adv_embedded/labs/lab2/lab1.srcs/sources_1/ip/chipscope_ila_v1_05_a_0/coregen.cgc"

set ipFile "c:/xup/adv_embedded/labs/lab2/lab1.srcs/sources_1/ip/chipscope_ila_v1_05_a_0/chipscope_ila_v1_05_a_0.xco"

set ipName "chipscope_ila_v1_05_a_0"

set vlnv "xilinx.com:ip:chipscope_ila:1.05.a"

set cgPartSpec "xc7z020-1clg484"

set bomFilePath "c:/xup/adv_embedded/labs/lab2/lab1.srcs/sources_1/ip/chipscope_ila_v1_05_a_0/pa_cg_bom.xml"

set hdlType "VHDL"

set chains "CUSTOMIZE_CURRENT_CHAIN INSTANTIATION_TEMPLATES_CHAIN"

# configure the IP
set result [source "c:/Xilinx/14.4/ISE_DS/PlanAhead/scripts/pa_cg_config_core.tcl"]

exit $result

